from pathlib import Path
import re
import subprocess
import textwrap
import sys

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from Agentic_AI.desktop_assistant_swarm.agents.workers import personal_worker
from Agentic_AI.desktop_assistant_swarm.tools.codebase_tools import get_python_file_errors, write_workspace_file


def _looks_like_code_task(request_text: str) -> bool:
    lowered = request_text.lower()
    return any(
        phrase in lowered
        for phrase in (
            "create a file",
            "write a python program",
            "write python program",
            "bubble_sort",
            "bubble sort",
            "execute it",
            "run it",
            "code",
        )
    )


def _extract_target_folder(request_text: str) -> str:
    match = re.search(r"\bin\s+([A-Za-z0-9_./\\-]+)", request_text, re.IGNORECASE)
    if match:
        return match.group(1).strip(" .\\/")
    return "RAG"


def _extract_program_topic(request_text: str) -> str:
    lowered = request_text.lower()
    if "bubble sort" in lowered or "bubble_sort" in lowered:
        return "bubble_sort"
    if "hello world" in lowered:
        return "hello_world"

    match = re.search(r"on\s+([A-Za-z0-9_./\\-]+)", request_text, re.IGNORECASE)
    if match:
        return match.group(1).strip(" .\\/")

    return "program"


def _build_python_program(topic: str) -> str:
    normalized_topic = topic.lower().replace("-", "_").replace(" ", "_")
    if normalized_topic == "bubble_sort":
        return textwrap.dedent(
            '''
            """Simple bubble sort demo program."""


            def bubble_sort(numbers: list[int]) -> list[int]:
                items = numbers[:]
                item_count = len(items)
                for outer_index in range(item_count):
                    swapped = False
                    for inner_index in range(0, item_count - outer_index - 1):
                        if items[inner_index] > items[inner_index + 1]:
                            items[inner_index], items[inner_index + 1] = items[inner_index + 1], items[inner_index]
                            swapped = True
                    if not swapped:
                        break
                return items


            def main() -> None:
                sample_numbers = [64, 34, 25, 12, 22, 11, 90]
                print("Input:", sample_numbers)
                print("Sorted:", bubble_sort(sample_numbers))


            if __name__ == "__main__":
                main()
            '''
        ).strip() + "\n"

    if normalized_topic == "hello_world":
        return textwrap.dedent(
            '''
            """Simple hello world demo program."""


            def main() -> None:
                print("Hello, world!")


            if __name__ == "__main__":
                main()
            '''
        ).strip() + "\n"

    return textwrap.dedent(
        f'''
        """Auto-generated program for {topic}."""


        def main() -> None:
            print("Program topic: {topic}")
            print("This file was generated by the personal agent.")


        if __name__ == "__main__":
            main()
        '''
    ).strip() + "\n"


def _handle_code_task(request_text: str) -> str:
    target_folder = _extract_target_folder(request_text)
    topic = _extract_program_topic(request_text)
    file_name = f"{topic}.py" if topic.endswith(".py") is False else topic
    target_path = f"{target_folder}/{file_name}".replace("//", "/")
    absolute_target_path = Path(__file__).resolve().parents[2] / target_path
    script_content = _build_python_program(topic)

    write_result = write_workspace_file.invoke({"path_text": target_path, "content": script_content})
    syntax_result = get_python_file_errors.invoke({"path_text": target_path})
    execution = subprocess.run([sys.executable, str(absolute_target_path)], cwd=str(Path(__file__).resolve().parents[2]), capture_output=True, text=True)

    output_lines = [
        "--- Coding Task ---",
        f"Created file: {target_path}",
        f"Write result: {write_result}",
        f"Syntax check: {syntax_result}",
        "",
        "Execution output:",
        execution.stdout.strip() or "<no stdout>",
    ]

    if execution.stderr.strip():
        output_lines.extend(["", "Execution errors:", execution.stderr.strip()])

    return "\n".join(output_lines)


def _extract_final_message(result) -> str:
    messages = result.get("messages", []) if isinstance(result, dict) else []
    if not messages:
        return "No response was produced by the personal agent."

    final_message = messages[-1]
    return getattr(final_message, "content", str(final_message))


def main() -> None:
    print("Personal agent mode")
    print("Ask for code changes, web research, file operations, or OS automation. Type 'exit' to quit.")

    while True:
        request_text = input("Request: ").strip()
        if not request_text:
            continue

        if request_text.lower() in {"exit", "quit", "q"}:
            print("Exiting personal agent mode.")
            break

        if _looks_like_code_task(request_text):
            print()
            print(_handle_code_task(request_text))
            print()
            continue

        result = personal_worker.invoke({"messages": [("user", request_text)]})
        print("\n--- Final Response ---")
        print(_extract_final_message(result))
        print()


if __name__ == "__main__":
    main()